DOMAIN = "actualbudget"
PLATFORM = "sensor"
DOMAIN_DATA = f"{DOMAIN}_data"

CONFIG_ENDPOINT = "endpoint"
CONFIG_PASSWORD = "password"
CONFIG_FILE = "file"
CONFIG_CURRENCY = "currency"
CONFIG_CERT = "cert"
CONFIG_ENCRYPT_PASSWORD = "encrypt_password"
