get_transactions:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: actualbudget
    account:
      required: false
      selector:
        text:
    category:
      required: false
      selector:
        text:
    start_date:
      required: false
      selector:
        date:
    end_date:
      required: false
      selector:
        date:
    is_parent:
      required: true
      selector:
        boolean:

commit:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: actualbudget

create_splits:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: actualbudget
    transaction:
      required: true
      selector:
        text:
    splits:
      required: true
      selector:
        object:
          label_field: category
          description_field: amount
          multiple: true
          translation_key: add_split
          fields:
            transfer:
              required: false
              selector:
                text:
            payee:
              required: false
              selector:
                text:
            category:
              required: false
              selector:
                text:
            amount:
              required: true
              selector:
                number:
                  mode: box

get_accounts:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: actualbudget
    account:
      required: false
      selector:
        text:
